### ISSUE TITLE
Feature request: hide previous "your PR failed on Travis" comments when posting a new one

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/highfive#202] opened 2019-03-17 10:47 UTC
These comments clutter the PR discussion thread, especially when people use CI to test their changes and these comments are created in numerous amount.

Unfortunately even deleted comments are counted by GitHub when it determines the thread as "long" and hides a part of it under the "N hidden items    Load more..." button.
So deleting comments doesn't have benefits over hiding, and hiding is preferable because there's still a small chance for the old comments to contain something valuable.

**Comment by petrochenkov** [comment] 2019-03-17 10:48
Same applies to old "merge conflict" comments from bors.

**Comment by kennytm** [comment] 2019-03-17 11:19
Unfortunately hiding is _still_ not exposed as a GitHub API (isaacs/github#1480).

**Comment by pietroalbini** [comment] 2019-03-17 12:27
Duplicate of https://github.com/rust-lang/rust-log-analyzer/issues/19

**Closed by pietroalbini** 2019-03-17 12:27 UTC
